# Based on https://iamkelv.in/blog/2017/08/weechat.html
---
- name: Ensure weechat is present
  become: true
  become_user: root
  dnf:
    name: weechat
    state: present

- name: Ensure tmux is present
  become: true
  become_user: root
  dnf:
    name: tmux
    state: present

- name: Ensure systemd user directory exists
  file:
    path: ~/.config/systemd/user
    state: directory

- name: Install weechat service
  template:
    src: weechat.service
    dest: ~/.config/systemd/user/weechat.service

- name: Register uid of '{{username}}'
  command: id -u {{username}}
  register: uid

- name: Start and enable weechat service
  systemd:
    name: weechat
    state: started
    enabled: yes
    user: yes
    daemon_reload: yes
  environment:
    XDG_RUNTIME_DIR: /run/user/{{uid.stdout}}

- name: Enable linger for '{{ username }}'
  become: true
  become_user: root
  command: loginctl enable-linger {{ username }}

- name: Ensure certbot installed
  become: true
  become_user: root
  dnf:
    name: weechat
    state: present

- name: Install python3 firewalld bindings
  become: true
  become_user: root
  dnf:
    name: python3-firewall
    state: present

- name: Open ports 80 and 443
  become: true
  become_user: root
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - 80
    - 443

- name: Run certbot command
  become: true
  become_user: root
  command: certbot certonly --standalone --noninteractive --agree-tos -d {{ weechat_domain }} -m {{ weechat_letsencrypt_email }}

- name: Ensure .weechat/ssl directory exists
  file:
    path: ~/.weechat/ssl
    state: directory

- name: Install weechat certificate renewal script
  become: true
  become_user: root
  template:
    src: renew-weechat.sh
    dest: /usr/local/sbin/renew-weechat.sh
    mode: 700

- name: Setup renewal script to run every Monday
  become: true
  become_user: root
  cron:
    name: renew weechat
    job: /usr/local/sbin/renew-weechat.sh
    hour: 0
    minute: 0
    weekday: 1
