---
# Tasks for setting up ruby development for epiGenesis

- name: install node
  apt:
    name: nodejs
    state: latest

- name: symlink /usr/bin/node to /usr/bin/nodejs
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link

- name: install bundler
  when: ansible_os_family == "Debian"
  apt:
    name: bundler 
    state: present

- name: install rails
  gem:
    name: rails
    version: 5.0.1
    state: present
