---
# Tasks for installing newest firefox

- name: check if firefox installed
  shell: "[ -d /opt/firefox ] && echo 'Found' || echo ''"
  register: firefox_installed

- name: check if firefox downloaded
  shell: "[ -f /tmp/firefox.tar.bz2 ] && echo 'Found' || echo ''"
  when: not firefox_installed.stdout
  register: firefox_tar_exists

- name: download firefox zip
  when: (not firefox_tar_exists) and (not firefox_installed)
  get_url:
    url: https://download.mozilla.org/?product=firefox-latest&os=win&lang=en-US
    dest: /tmp/firefox.tar.bz2
  register: firefox_downloaded

- name: extract firefox
  unarchive:
    src: /tmp/firefox.tar.bz2
    dest: /opt
  when: firefox_downloaded and (not firefox_installed)

- name: add firefox desktop entry
  copy:
    src: ../files/firefox.desktop
    dest: /usr/share/applications/firefox.desktop
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
