---
# Tasks for core desktop setup

- include: xfce4.yml
- include: urxvt.yml

- name: install xclip
  when: ansible_os_family == "Debian"
  apt:
    name: xclip
    state: present

- name: install redshift
  when: ansible_os_family == "Debian"
  apt:
    name: redshift
    state: present

- name: install mupdf
  when: ansible_os_family == "Debian"
  apt:
    name: mupdf
    state: present
