---
# Tasks for installing newest tor

- name: check if tor installed
  shell: "[ -d /opt/tor ] && echo 'Found' || echo ''"
  register: tor_installed

- name: check if tor downloaded
  shell: "[ -f /tmp/tor.tar.xz ] && echo 'Found' || echo ''"
  when: not tor_installed.stdout
  register: tor_tar_exists

- name: download tor zip
  when: (not tor_tar_exists.stdout) and (not tor_installed.stdout)
  get_url:
    url: https://www.torproject.org/dist/torbrowser/6.5.1/tor-browser-linux64-6.5.1_en-US.tar.xz
    dest: /tmp/tor.tar.xz
  register: tor_downloaded

- name: extract tor
  unarchive:
    src: /tmp/tor.tar.xz
    dest: /opt
  when: (tor_downloaded or tor_tar_exists.stdout) and (not tor_installed.stdout)

- name: add tor desktop entry
  copy:
    src: /opt/tor-browser_en-US/Browser/start-tor-browser.desktop
    dest: /usr/share/applications/start-tor-browser.desktop
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
