---
# Tasks for xfce4 setup

- name: install xfce and goodies
  when: ansible_os_family == "Debian"
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - xfce4
    - xfce4-battery-plugin
    - xfce4-power-manager
    - xfce4-power-manager-plugins
    - xfce4-clipman-plugin

- name: install numix theme
  when: ansible_os_family == "Debian"
  apt:
    name: numix-gtk-theme
    state: present
  register: numix

- name: install paper
  when: ansible_os_family == "Debian"
  shell: "dpkg -i {{ role_path }}/files/paper*.deb; apt-get install -f"
