---
- include: neovim.yml

- name: install core dev tools
  when: ansible_os_family == "Debian"
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - curl
    - git
    - stow
    - sudo
    - tmux
    - tree
    - unzip
    - vim

- name: install core dev tools
  when: ansible_os_family == "RedHat"
  dnf:
    name: "{{item}}"
    state: present
  with_items:
    - curl
    - git
    - stow
    - sudo
    - tmux
    - tree
    - unzip
    - vim
