---
# Core command line utiltity setup
- name: add neovim ppa
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'
  when: ansible_distribution == 'Ubuntu'

- name: install core dev tools
  when: ansible_os_family == "Debian"
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - curl
    - git
    - neovim
    - stow
    - sudo
    - tmux
    - tree
    - unzip
    - vim
    - zsh

- name: Creating 'wheel' group
  group:
    name: wheel
    state: present

- name: Allowing 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: create personal devel directory
  file:
    path: /home/{{ username }}/devel
    state: directory
  become: true
  become_user: "{{ username }}"

- name: clone dotfiles repo
  git:
    repo: https://github.com/cgmcintyr/dotfiles.git
    dest: /home/{{ username }}/dotfiles
    version: master
    accept_hostkey: yes
    update: true
  become: true
  become_user: "{{ username }}"

- name: ensure dotfiles are removed
  when: ansible_os_family == "Debian"
  file:
    path: "/home/{{ username }}/{{item}}"
    state: absent
  with_items:
    - ".bashrc"
    - ".bash_logout"
    - ".profile"

- name: stow dotfiles
  become: true
  become_user: "{{ username }}"
  shell: "cd /home/{{ username }}/dotfiles && stow -R * -v"
