---
# Core command line utiltity setup
- name: install email utilities
  when: ansible_os_family == "Debian"
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - mutt
    - offlineimap
    - msmtp

- name: Create cron job to sync offlineimap
  cron:
    name: "offline imap sync"
    minute: "*/3"
    user: "{{ username }}"
    job: "/usr/bin/offlineimap -o -u quiet"
  become: true
  become_user: "{{ username }}"
