---
# Core command line utiltity setup
- name: install email utilities
  when: ansible_os_family == "Debian"
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - mutt
    - offlineimap
    - msmtp
