---
- name: Make sure 'wheel' and 'ssh-user' groups exist
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - wheel
    - ssh-user

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'


- name: Creating default user '{{ username }}'
  user:
    name: "{{ username }}"
    comment: "{{ gecos }}"
    groups:
      - wheel
      - ssh-user
    shell: /bin/zsh
    createhome: yes
    state: present

- name: Add authorized keys
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key_personal }}"

- name: Remove '{{ username }}'\'s password
  command: passwd -d {{ username }}
